### ISSUE TITLE
Save Image, Copy Image address missing from Context menu

### ISSUE THREAD

**Issue by realandrewjose** [flameskyofficial/FlameSky#17]
Please ensure that one is able to save an image or copy image address by using the context menu.

**Comment by realandrewjose** [comment]
@novastream I also need help here Jonathan. Can you help me here with a pull request?

**Comment by andrewjoseofficial** [comment]
*here

**Comment by realandrewjose** [comment]
@novastream , You are also our first contributor. You are also a developer of FlameSky, and are key to its success. As mentioned in our website, FlameSky is developed by FlameSky Contributors. Thank you.

**Comment by realandrewjose** [comment]
@novastream Also, please make a pull request to the 5.0.0.0 branch. I am planning on using branches

**Comment by realandrewjose** [comment]
@novastream Hi, a change. I believe it is more easier working with master branch. So dont worry, you can commit to master.

**Comment by andrewjoseofficial** [comment]
@novastream  I also sent you an invitation to become a member of 'FlameSky Organization'. This gives you access to our respositories.

**Comment by realandrewjose** [comment]
@novastream If you dont want to join FlameSky org, and want to just be an outside collaborators, thats fine too. No pressure

**Comment by novastream** [comment]
@andrewjoseofficial where you able to merge? I think you only need to merge the MenuHandler file and you will be good :)

**Comment by realandrewjose** [comment]
@novastream  The issue, is that I was not able to merge. So can you edit the changes in master.

**Comment by realandrewjose** [comment]
@novastream 5.0 beta released John. I dont think I may continue development beyond 5.0
