### ISSUE TITLE
Need help to store data from datatable in FlameSky notes app

### ISSUE THREAD

**Issue by realandrewjose** [flameskyofficial/FlameSky#30]
The notes stored, are not retrieved when the app goes through a new instance. The intended feature was notes to be stored until deletion. Can anyone help me?

**Comment by realandrewjose** [comment]
I worked on some aspects of it, just need help with data storage - thats it. And contributers, feel free to add more features as you think will be necessary.

**Comment by realandrewjose** [comment]
@novastream Since you are better experienced in C#, can you help with this too. I made the UI, and basic functionality so far. I need help with saving it. Also, please add more features to notes, and remove what you think are too problematic.

**Comment by andrewjoseofficial** [comment]
@novastream Due to difficulties maintaining this project, and the need to focus on school, I am going to close this project until further notice, Jonathan. Thanks for your help in the project. Don't worry, you will always be credited (github.com/flameskyoffical/ contributor tab). I want to focus more on the school.

**Comment by realandrewjose** [comment]
@novastream  After version 5.0.0.0, I am going to archive this repository until further notice. Thanks for your help as FlameSky contributor, Johnathan

**Comment by realandrewjose** [comment]
FlameSky Notes is a sticky notes applet now.

**Comment by realandrewjose** [comment]
@novastream I am sorry for forgetting to ask your thoughts. Can I archive this project? You can fork this and develop on it Johnathan. I began this thinking I can maintain it. But I dont think I can sustain it with commitment. Please let me know.
